//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPlatformService {
    
    
    public partial class NoSecurity {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SPlatformService.Shared.MasterPage Master {
            get {
                return ((SPlatformService.Shared.MasterPage)(base.Master));
            }
        }
    }
}
